### ISSUE TITLE
Migrate CSS Files

### ISSUE THREAD

**Issue by RajVarsani** [Uthaan-IIITM/Uthaan-Frontend#57]
### Describe your issue.

We're currently using regular CSS, but as the number of files is getting larger, there may raise some conflicts in class names. To resolve it, we can use modular CSS instead of normal one.

### Instructions:

- Rename files: `.css` to `.module.css`
- update class names. ex: `home-page-container` to `container`
- update import: `import "style.css"` to `import styles from " styles.module.css"`
- usage:  `"className"` to `{styles.className}.`

> multiple contributors are welcome as many files to be changed.

**Comment by kaustav202** [comment]
can I work on this?

**Comment by RajVarsani** [comment]
Sure.
Make sure to create a draft PR and keep continuously updating regarding the progress. Please maintain a checklist of subtasks in PR for the same.

**Comment by shikhar13012001** [comment]
Is this still open , I would like to work on it.@RajVarsani

**Comment by RajVarsani** [comment]
Yes @shikhar13012001 it is open. You may work on this.

**Comment by varunKT001** [comment]
@RajVarsani I would like to work on it.
